/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by apiregister-gen. DO NOT EDIT.

package demo

import (
	"context"
	"fmt"

	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/registry/rest"
	"sigs.k8s.io/apiserver-builder-alpha/pkg/builders"
)

var (
	DemoDemoStorage = builders.NewApiResource( // Resource status endpoint
		InternalDemo,
		func() runtime.Object { return &Demo{} },     // Register versioned resource
		func() runtime.Object { return &DemoList{} }, // Register versioned resource list
		&DemoStrategy{builders.StorageStrategySingleton},
	)
	InternalDemo = builders.NewInternalResource(
		"demos",
		"Demo",
		func() runtime.Object { return &Demo{} },
		func() runtime.Object { return &DemoList{} },
	)
	InternalDemoStatus = builders.NewInternalResourceStatus(
		"demos",
		"DemoStatus",
		func() runtime.Object { return &Demo{} },
		func() runtime.Object { return &DemoList{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewApiGroup("demo.myproject").WithKinds(
		InternalDemo,
		InternalDemoStatus,
	)

	// Required by code generated by go2idl
	AddToScheme = (&runtime.SchemeBuilder{
		ApiVersion.SchemeBuilder.AddToScheme,
		RegisterDefaults,
	}).AddToScheme
	SchemeBuilder      = ApiVersion.SchemeBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type Demo struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   DemoSpec
	Status DemoStatus
}

type DemoSpec struct {
}

type DemoStatus struct {
}

//
// Demo Functions and Structs
//
// +k8s:deepcopy-gen=false
type DemoStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type DemoStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type DemoList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []Demo
}

func (Demo) NewStatus() interface{} {
	return DemoStatus{}
}

func (pc *Demo) GetStatus() interface{} {
	return pc.Status
}

func (pc *Demo) SetStatus(s interface{}) {
	pc.Status = s.(DemoStatus)
}

func (pc *Demo) GetSpec() interface{} {
	return pc.Spec
}

func (pc *Demo) SetSpec(s interface{}) {
	pc.Spec = s.(DemoSpec)
}

func (pc *Demo) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *Demo) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc Demo) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store Demo.
// +k8s:deepcopy-gen=false
type DemoRegistry interface {
	ListDemos(ctx context.Context, options *internalversion.ListOptions) (*DemoList, error)
	GetDemo(ctx context.Context, id string, options *metav1.GetOptions) (*Demo, error)
	CreateDemo(ctx context.Context, id *Demo) (*Demo, error)
	UpdateDemo(ctx context.Context, id *Demo) (*Demo, error)
	DeleteDemo(ctx context.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewDemoRegistry(sp builders.StandardStorageProvider) DemoRegistry {
	return &storageDemo{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageDemo struct {
	builders.StandardStorageProvider
}

func (s *storageDemo) ListDemos(ctx context.Context, options *internalversion.ListOptions) (*DemoList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*DemoList), err
}

func (s *storageDemo) GetDemo(ctx context.Context, id string, options *metav1.GetOptions) (*Demo, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*Demo), nil
}

func (s *storageDemo) CreateDemo(ctx context.Context, object *Demo) (*Demo, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, nil, &metav1.CreateOptions{})
	if err != nil {
		return nil, err
	}
	return obj.(*Demo), nil
}

func (s *storageDemo) UpdateDemo(ctx context.Context, object *Demo) (*Demo, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object), nil, nil, false, &metav1.UpdateOptions{})
	if err != nil {
		return nil, err
	}
	return obj.(*Demo), nil
}

func (s *storageDemo) DeleteDemo(ctx context.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil, &metav1.DeleteOptions{})
	return sync, err
}
